### PR TITLE
Created a scope to resolve services from

### PR DESCRIPTION
**Pull request by Xeythhhh**
This resolves scoped services and nested scopes

### CODE REVIEW

**Review by XeroxDev — COMMENTED** [review]
Is there a possibility to break something? (as example services which aren't scoped)

**Comment by Xeythhhh** [comment]
There's no way this breaks anything. But I have to check if the scope is disposed properly now that I think about it.

**Comment by Xeythhhh** [comment]
Looks good from my tests. No memory leaks after and all service types are resolved correctly.

**Review by XeroxDev — APPROVED** [review]

**Comment by XeroxDev** [comment]
If the hooks work as intended, the changes should be live soon!

**Pull request merged**
